// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OWLSMEVENTS_OWLSM_FB_H_
#define FLATBUFFERS_GENERATED_OWLSMEVENTS_OWLSM_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace owlsm {
namespace fb {

struct Owner;

struct StdioFileDescriptors;

struct File;
struct FileBuilder;

struct Process;
struct ProcessBuilder;

struct RuleMetadata;
struct RuleMetadataBuilder;

struct Target;
struct TargetBuilder;

struct ChmodInfo;
struct ChmodInfoBuilder;

struct ChownInfo;
struct ChownInfoBuilder;

struct RenameInfo;
struct RenameInfoBuilder;

struct NetworkInfo;
struct NetworkInfoBuilder;

struct DnsAnswer;
struct DnsAnswerBuilder;

struct DnsQueryInfo;
struct DnsQueryInfoBuilder;

struct DnsResponseInfo;
struct DnsResponseInfoBuilder;

struct GenericFileEventData;
struct GenericFileEventDataBuilder;

struct ChownEventData;
struct ChownEventDataBuilder;

struct ChmodEventData;
struct ChmodEventDataBuilder;

struct ExecEventData;
struct ExecEventDataBuilder;

struct ForkEventData;
struct ForkEventDataBuilder;

struct ExitEventData;
struct ExitEventDataBuilder;

struct RenameEventData;
struct RenameEventDataBuilder;

struct NetworkEventData;
struct NetworkEventDataBuilder;

struct DnsQueryEventData;
struct DnsQueryEventDataBuilder;

struct DnsResponseEventData;
struct DnsResponseEventDataBuilder;

struct Event;
struct EventBuilder;

struct Error;
struct ErrorBuilder;

enum class EventType : uint8_t {
  EXEC = 0,
  FORK = 1,
  EXIT = 2,
  FILE_CREATE = 3,
  UNLINK = 4,
  MKDIR = 5,
  RMDIR = 6,
  CHMOD = 7,
  CHOWN = 8,
  WRITE = 9,
  READ = 10,
  RENAME = 11,
  NETWORK = 12,
  DNS_QUERY = 13,
  DNS_RESPONSE = 14,
  MIN = EXEC,
  MAX = DNS_RESPONSE
};

inline const EventType (&EnumValuesEventType())[15] {
  static const EventType values[] = {
    EventType::EXEC,
    EventType::FORK,
    EventType::EXIT,
    EventType::FILE_CREATE,
    EventType::UNLINK,
    EventType::MKDIR,
    EventType::RMDIR,
    EventType::CHMOD,
    EventType::CHOWN,
    EventType::WRITE,
    EventType::READ,
    EventType::RENAME,
    EventType::NETWORK,
    EventType::DNS_QUERY,
    EventType::DNS_RESPONSE
  };
  return values;
}

inline const char * const *EnumNamesEventType() {
  static const char * const names[16] = {
    "EXEC",
    "FORK",
    "EXIT",
    "FILE_CREATE",
    "UNLINK",
    "MKDIR",
    "RMDIR",
    "CHMOD",
    "CHOWN",
    "WRITE",
    "READ",
    "RENAME",
    "NETWORK",
    "DNS_QUERY",
    "DNS_RESPONSE",
    nullptr
  };
  return names;
}

inline const char *EnumNameEventType(EventType e) {
  if (::flatbuffers::IsOutRange(e, EventType::EXEC, EventType::DNS_RESPONSE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEventType()[index];
}

enum class Action : uint8_t {
  ALLOW_EVENT = 0,
  BLOCK_EVENT = 1,
  BLOCK_KILL_PROCESS = 2,
  BLOCK_KILL_PROCESS_KILL_PARENT = 3,
  KILL_PROCESS = 4,
  EXCLUDE_EVENT = 5,
  MIN = ALLOW_EVENT,
  MAX = EXCLUDE_EVENT
};

inline const Action (&EnumValuesAction())[6] {
  static const Action values[] = {
    Action::ALLOW_EVENT,
    Action::BLOCK_EVENT,
    Action::BLOCK_KILL_PROCESS,
    Action::BLOCK_KILL_PROCESS_KILL_PARENT,
    Action::KILL_PROCESS,
    Action::EXCLUDE_EVENT
  };
  return values;
}

inline const char * const *EnumNamesAction() {
  static const char * const names[7] = {
    "ALLOW_EVENT",
    "BLOCK_EVENT",
    "BLOCK_KILL_PROCESS",
    "BLOCK_KILL_PROCESS_KILL_PARENT",
    "KILL_PROCESS",
    "EXCLUDE_EVENT",
    nullptr
  };
  return names;
}

inline const char *EnumNameAction(Action e) {
  if (::flatbuffers::IsOutRange(e, Action::ALLOW_EVENT, Action::EXCLUDE_EVENT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAction()[index];
}

enum class FileType : uint8_t {
  UNKNOWN_FILE_TYPE = 0,
  DIRECTORY = 1,
  SYMLINK = 2,
  BLOCK_DEVICE = 3,
  CHAR_DEVICE = 4,
  REGULAR_FILE = 5,
  SOCKET = 6,
  FIFO = 7,
  NO_FILE = 8,
  MIN = UNKNOWN_FILE_TYPE,
  MAX = NO_FILE
};

inline const FileType (&EnumValuesFileType())[9] {
  static const FileType values[] = {
    FileType::UNKNOWN_FILE_TYPE,
    FileType::DIRECTORY,
    FileType::SYMLINK,
    FileType::BLOCK_DEVICE,
    FileType::CHAR_DEVICE,
    FileType::REGULAR_FILE,
    FileType::SOCKET,
    FileType::FIFO,
    FileType::NO_FILE
  };
  return values;
}

inline const char * const *EnumNamesFileType() {
  static const char * const names[10] = {
    "UNKNOWN_FILE_TYPE",
    "DIRECTORY",
    "SYMLINK",
    "BLOCK_DEVICE",
    "CHAR_DEVICE",
    "REGULAR_FILE",
    "SOCKET",
    "FIFO",
    "NO_FILE",
    nullptr
  };
  return names;
}

inline const char *EnumNameFileType(FileType e) {
  if (::flatbuffers::IsOutRange(e, FileType::UNKNOWN_FILE_TYPE, FileType::NO_FILE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesFileType()[index];
}

enum class ConnectionDirection : uint8_t {
  INCOMING = 0,
  OUTGOING = 1,
  MIN = INCOMING,
  MAX = OUTGOING
};

inline const ConnectionDirection (&EnumValuesConnectionDirection())[2] {
  static const ConnectionDirection values[] = {
    ConnectionDirection::INCOMING,
    ConnectionDirection::OUTGOING
  };
  return values;
}

inline const char * const *EnumNamesConnectionDirection() {
  static const char * const names[3] = {
    "INCOMING",
    "OUTGOING",
    nullptr
  };
  return names;
}

inline const char *EnumNameConnectionDirection(ConnectionDirection e) {
  if (::flatbuffers::IsOutRange(e, ConnectionDirection::INCOMING, ConnectionDirection::OUTGOING)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesConnectionDirection()[index];
}

enum class EventData : uint8_t {
  NONE = 0,
  GenericFileEventData = 1,
  ChownEventData = 2,
  ChmodEventData = 3,
  ExecEventData = 4,
  ForkEventData = 5,
  ExitEventData = 6,
  RenameEventData = 7,
  NetworkEventData = 8,
  DnsQueryEventData = 9,
  DnsResponseEventData = 10,
  MIN = NONE,
  MAX = DnsResponseEventData
};

inline const EventData (&EnumValuesEventData())[11] {
  static const EventData values[] = {
    EventData::NONE,
    EventData::GenericFileEventData,
    EventData::ChownEventData,
    EventData::ChmodEventData,
    EventData::ExecEventData,
    EventData::ForkEventData,
    EventData::ExitEventData,
    EventData::RenameEventData,
    EventData::NetworkEventData,
    EventData::DnsQueryEventData,
    EventData::DnsResponseEventData
  };
  return values;
}

inline const char * const *EnumNamesEventData() {
  static const char * const names[12] = {
    "NONE",
    "GenericFileEventData",
    "ChownEventData",
    "ChmodEventData",
    "ExecEventData",
    "ForkEventData",
    "ExitEventData",
    "RenameEventData",
    "NetworkEventData",
    "DnsQueryEventData",
    "DnsResponseEventData",
    nullptr
  };
  return names;
}

inline const char *EnumNameEventData(EventData e) {
  if (::flatbuffers::IsOutRange(e, EventData::NONE, EventData::DnsResponseEventData)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEventData()[index];
}

template<typename T> struct EventDataTraits {
  static const EventData enum_value = EventData::NONE;
};

template<> struct EventDataTraits<owlsm::fb::GenericFileEventData> {
  static const EventData enum_value = EventData::GenericFileEventData;
};

template<> struct EventDataTraits<owlsm::fb::ChownEventData> {
  static const EventData enum_value = EventData::ChownEventData;
};

template<> struct EventDataTraits<owlsm::fb::ChmodEventData> {
  static const EventData enum_value = EventData::ChmodEventData;
};

template<> struct EventDataTraits<owlsm::fb::ExecEventData> {
  static const EventData enum_value = EventData::ExecEventData;
};

template<> struct EventDataTraits<owlsm::fb::ForkEventData> {
  static const EventData enum_value = EventData::ForkEventData;
};

template<> struct EventDataTraits<owlsm::fb::ExitEventData> {
  static const EventData enum_value = EventData::ExitEventData;
};

template<> struct EventDataTraits<owlsm::fb::RenameEventData> {
  static const EventData enum_value = EventData::RenameEventData;
};

template<> struct EventDataTraits<owlsm::fb::NetworkEventData> {
  static const EventData enum_value = EventData::NetworkEventData;
};

template<> struct EventDataTraits<owlsm::fb::DnsQueryEventData> {
  static const EventData enum_value = EventData::DnsQueryEventData;
};

template<> struct EventDataTraits<owlsm::fb::DnsResponseEventData> {
  static const EventData enum_value = EventData::DnsResponseEventData;
};

template <bool B = false>
bool VerifyEventData(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, EventData type);
template <bool B = false>
bool VerifyEventDataVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<EventData> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Owner FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t uid_;
  uint32_t gid_;

 public:
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.Owner";
  }
  Owner()
      : uid_(0),
        gid_(0) {
  }
  Owner(uint32_t _uid, uint32_t _gid)
      : uid_(::flatbuffers::EndianScalar(_uid)),
        gid_(::flatbuffers::EndianScalar(_gid)) {
  }
  uint32_t uid() const {
    return ::flatbuffers::EndianScalar(uid_);
  }
  uint32_t gid() const {
    return ::flatbuffers::EndianScalar(gid_);
  }
};
FLATBUFFERS_STRUCT_END(Owner, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) StdioFileDescriptors FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t stdin_;
  uint8_t stdout_;
  uint8_t stderr_;

 public:
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.StdioFileDescriptors";
  }
  StdioFileDescriptors()
      : stdin_(0),
        stdout_(0),
        stderr_(0) {
  }
  StdioFileDescriptors(owlsm::fb::FileType _stdin, owlsm::fb::FileType _stdout, owlsm::fb::FileType _stderr)
      : stdin_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_stdin))),
        stdout_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_stdout))),
        stderr_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_stderr))) {
  }
  owlsm::fb::FileType stdin() const {
    return static_cast<owlsm::fb::FileType>(::flatbuffers::EndianScalar(stdin_));
  }
  owlsm::fb::FileType stdout() const {
    return static_cast<owlsm::fb::FileType>(::flatbuffers::EndianScalar(stdout_));
  }
  owlsm::fb::FileType stderr() const {
    return static_cast<owlsm::fb::FileType>(::flatbuffers::EndianScalar(stderr_));
  }
};
FLATBUFFERS_STRUCT_END(StdioFileDescriptors, 3);

struct File FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FileBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.File";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INODE = 4,
    VT_DEV = 6,
    VT_PATH = 8,
    VT_OWNER = 10,
    VT_MODE = 12,
    VT_TYPE = 14,
    VT_SUID = 16,
    VT_SGID = 18,
    VT_LAST_MODIFIED_SECONDS = 20,
    VT_NLINK = 22,
    VT_FILENAME = 24
  };
  uint64_t inode() const {
    return GetField<uint64_t>(VT_INODE, 0);
  }
  uint32_t dev() const {
    return GetField<uint32_t>(VT_DEV, 0);
  }
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  const owlsm::fb::Owner *owner() const {
    return GetStruct<const owlsm::fb::Owner *>(VT_OWNER);
  }
  uint16_t mode() const {
    return GetField<uint16_t>(VT_MODE, 0);
  }
  owlsm::fb::FileType type() const {
    return static_cast<owlsm::fb::FileType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  uint8_t suid() const {
    return GetField<uint8_t>(VT_SUID, 0);
  }
  uint8_t sgid() const {
    return GetField<uint8_t>(VT_SGID, 0);
  }
  uint64_t last_modified_seconds() const {
    return GetField<uint64_t>(VT_LAST_MODIFIED_SECONDS, 0);
  }
  uint32_t nlink() const {
    return GetField<uint32_t>(VT_NLINK, 0);
  }
  const ::flatbuffers::String *filename() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FILENAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_INODE, 8) &&
           VerifyField<uint32_t>(verifier, VT_DEV, 4) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           VerifyField<owlsm::fb::Owner>(verifier, VT_OWNER, 4) &&
           VerifyField<uint16_t>(verifier, VT_MODE, 2) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_SUID, 1) &&
           VerifyField<uint8_t>(verifier, VT_SGID, 1) &&
           VerifyField<uint64_t>(verifier, VT_LAST_MODIFIED_SECONDS, 8) &&
           VerifyField<uint32_t>(verifier, VT_NLINK, 4) &&
           VerifyOffset(verifier, VT_FILENAME) &&
           verifier.VerifyString(filename()) &&
           verifier.EndTable();
  }
};

struct FileBuilder {
  typedef File Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_inode(uint64_t inode) {
    fbb_.AddElement<uint64_t>(File::VT_INODE, inode, 0);
  }
  void add_dev(uint32_t dev) {
    fbb_.AddElement<uint32_t>(File::VT_DEV, dev, 0);
  }
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(File::VT_PATH, path);
  }
  void add_owner(const owlsm::fb::Owner *owner) {
    fbb_.AddStruct(File::VT_OWNER, owner);
  }
  void add_mode(uint16_t mode) {
    fbb_.AddElement<uint16_t>(File::VT_MODE, mode, 0);
  }
  void add_type(owlsm::fb::FileType type) {
    fbb_.AddElement<uint8_t>(File::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_suid(uint8_t suid) {
    fbb_.AddElement<uint8_t>(File::VT_SUID, suid, 0);
  }
  void add_sgid(uint8_t sgid) {
    fbb_.AddElement<uint8_t>(File::VT_SGID, sgid, 0);
  }
  void add_last_modified_seconds(uint64_t last_modified_seconds) {
    fbb_.AddElement<uint64_t>(File::VT_LAST_MODIFIED_SECONDS, last_modified_seconds, 0);
  }
  void add_nlink(uint32_t nlink) {
    fbb_.AddElement<uint32_t>(File::VT_NLINK, nlink, 0);
  }
  void add_filename(::flatbuffers::Offset<::flatbuffers::String> filename) {
    fbb_.AddOffset(File::VT_FILENAME, filename);
  }
  explicit FileBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<File> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<File>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<File> CreateFile(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t inode = 0,
    uint32_t dev = 0,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0,
    const owlsm::fb::Owner *owner = nullptr,
    uint16_t mode = 0,
    owlsm::fb::FileType type = owlsm::fb::FileType::UNKNOWN_FILE_TYPE,
    uint8_t suid = 0,
    uint8_t sgid = 0,
    uint64_t last_modified_seconds = 0,
    uint32_t nlink = 0,
    ::flatbuffers::Offset<::flatbuffers::String> filename = 0) {
  FileBuilder builder_(_fbb);
  builder_.add_last_modified_seconds(last_modified_seconds);
  builder_.add_inode(inode);
  builder_.add_filename(filename);
  builder_.add_nlink(nlink);
  builder_.add_owner(owner);
  builder_.add_path(path);
  builder_.add_dev(dev);
  builder_.add_mode(mode);
  builder_.add_sgid(sgid);
  builder_.add_suid(suid);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<File> CreateFileDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t inode = 0,
    uint32_t dev = 0,
    const char *path = nullptr,
    const owlsm::fb::Owner *owner = nullptr,
    uint16_t mode = 0,
    owlsm::fb::FileType type = owlsm::fb::FileType::UNKNOWN_FILE_TYPE,
    uint8_t suid = 0,
    uint8_t sgid = 0,
    uint64_t last_modified_seconds = 0,
    uint32_t nlink = 0,
    const char *filename = nullptr) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  auto filename__ = filename ? _fbb.CreateString(filename) : 0;
  return owlsm::fb::CreateFile(
      _fbb,
      inode,
      dev,
      path__,
      owner,
      mode,
      type,
      suid,
      sgid,
      last_modified_seconds,
      nlink,
      filename__);
}

struct Process FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ProcessBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.Process";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PID = 4,
    VT_PPID = 6,
    VT_RUID = 8,
    VT_RGID = 10,
    VT_EUID = 12,
    VT_EGID = 14,
    VT_SUID = 16,
    VT_CGROUP_ID = 18,
    VT_START_TIME = 20,
    VT_PTRACE_FLAGS = 22,
    VT_FILE = 24,
    VT_CMD = 26,
    VT_STDIO_FILE_DESCRIPTORS_AT_PROCESS_CREATION = 28,
    VT_SHELL_COMMAND = 30
  };
  uint32_t pid() const {
    return GetField<uint32_t>(VT_PID, 0);
  }
  uint32_t ppid() const {
    return GetField<uint32_t>(VT_PPID, 0);
  }
  uint32_t ruid() const {
    return GetField<uint32_t>(VT_RUID, 0);
  }
  uint32_t rgid() const {
    return GetField<uint32_t>(VT_RGID, 0);
  }
  uint32_t euid() const {
    return GetField<uint32_t>(VT_EUID, 0);
  }
  uint32_t egid() const {
    return GetField<uint32_t>(VT_EGID, 0);
  }
  uint32_t suid() const {
    return GetField<uint32_t>(VT_SUID, 0);
  }
  uint64_t cgroup_id() const {
    return GetField<uint64_t>(VT_CGROUP_ID, 0);
  }
  uint64_t start_time() const {
    return GetField<uint64_t>(VT_START_TIME, 0);
  }
  uint32_t ptrace_flags() const {
    return GetField<uint32_t>(VT_PTRACE_FLAGS, 0);
  }
  const owlsm::fb::File *file() const {
    return GetPointer<const owlsm::fb::File *>(VT_FILE);
  }
  const ::flatbuffers::String *cmd() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CMD);
  }
  const owlsm::fb::StdioFileDescriptors *stdio_file_descriptors_at_process_creation() const {
    return GetStruct<const owlsm::fb::StdioFileDescriptors *>(VT_STDIO_FILE_DESCRIPTORS_AT_PROCESS_CREATION);
  }
  const ::flatbuffers::String *shell_command() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SHELL_COMMAND);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PID, 4) &&
           VerifyField<uint32_t>(verifier, VT_PPID, 4) &&
           VerifyField<uint32_t>(verifier, VT_RUID, 4) &&
           VerifyField<uint32_t>(verifier, VT_RGID, 4) &&
           VerifyField<uint32_t>(verifier, VT_EUID, 4) &&
           VerifyField<uint32_t>(verifier, VT_EGID, 4) &&
           VerifyField<uint32_t>(verifier, VT_SUID, 4) &&
           VerifyField<uint64_t>(verifier, VT_CGROUP_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_START_TIME, 8) &&
           VerifyField<uint32_t>(verifier, VT_PTRACE_FLAGS, 4) &&
           VerifyOffset(verifier, VT_FILE) &&
           verifier.VerifyTable(file()) &&
           VerifyOffset(verifier, VT_CMD) &&
           verifier.VerifyString(cmd()) &&
           VerifyField<owlsm::fb::StdioFileDescriptors>(verifier, VT_STDIO_FILE_DESCRIPTORS_AT_PROCESS_CREATION, 1) &&
           VerifyOffset(verifier, VT_SHELL_COMMAND) &&
           verifier.VerifyString(shell_command()) &&
           verifier.EndTable();
  }
};

struct ProcessBuilder {
  typedef Process Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pid(uint32_t pid) {
    fbb_.AddElement<uint32_t>(Process::VT_PID, pid, 0);
  }
  void add_ppid(uint32_t ppid) {
    fbb_.AddElement<uint32_t>(Process::VT_PPID, ppid, 0);
  }
  void add_ruid(uint32_t ruid) {
    fbb_.AddElement<uint32_t>(Process::VT_RUID, ruid, 0);
  }
  void add_rgid(uint32_t rgid) {
    fbb_.AddElement<uint32_t>(Process::VT_RGID, rgid, 0);
  }
  void add_euid(uint32_t euid) {
    fbb_.AddElement<uint32_t>(Process::VT_EUID, euid, 0);
  }
  void add_egid(uint32_t egid) {
    fbb_.AddElement<uint32_t>(Process::VT_EGID, egid, 0);
  }
  void add_suid(uint32_t suid) {
    fbb_.AddElement<uint32_t>(Process::VT_SUID, suid, 0);
  }
  void add_cgroup_id(uint64_t cgroup_id) {
    fbb_.AddElement<uint64_t>(Process::VT_CGROUP_ID, cgroup_id, 0);
  }
  void add_start_time(uint64_t start_time) {
    fbb_.AddElement<uint64_t>(Process::VT_START_TIME, start_time, 0);
  }
  void add_ptrace_flags(uint32_t ptrace_flags) {
    fbb_.AddElement<uint32_t>(Process::VT_PTRACE_FLAGS, ptrace_flags, 0);
  }
  void add_file(::flatbuffers::Offset<owlsm::fb::File> file) {
    fbb_.AddOffset(Process::VT_FILE, file);
  }
  void add_cmd(::flatbuffers::Offset<::flatbuffers::String> cmd) {
    fbb_.AddOffset(Process::VT_CMD, cmd);
  }
  void add_stdio_file_descriptors_at_process_creation(const owlsm::fb::StdioFileDescriptors *stdio_file_descriptors_at_process_creation) {
    fbb_.AddStruct(Process::VT_STDIO_FILE_DESCRIPTORS_AT_PROCESS_CREATION, stdio_file_descriptors_at_process_creation);
  }
  void add_shell_command(::flatbuffers::Offset<::flatbuffers::String> shell_command) {
    fbb_.AddOffset(Process::VT_SHELL_COMMAND, shell_command);
  }
  explicit ProcessBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Process> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Process>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Process> CreateProcess(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t pid = 0,
    uint32_t ppid = 0,
    uint32_t ruid = 0,
    uint32_t rgid = 0,
    uint32_t euid = 0,
    uint32_t egid = 0,
    uint32_t suid = 0,
    uint64_t cgroup_id = 0,
    uint64_t start_time = 0,
    uint32_t ptrace_flags = 0,
    ::flatbuffers::Offset<owlsm::fb::File> file = 0,
    ::flatbuffers::Offset<::flatbuffers::String> cmd = 0,
    const owlsm::fb::StdioFileDescriptors *stdio_file_descriptors_at_process_creation = nullptr,
    ::flatbuffers::Offset<::flatbuffers::String> shell_command = 0) {
  ProcessBuilder builder_(_fbb);
  builder_.add_start_time(start_time);
  builder_.add_cgroup_id(cgroup_id);
  builder_.add_shell_command(shell_command);
  builder_.add_stdio_file_descriptors_at_process_creation(stdio_file_descriptors_at_process_creation);
  builder_.add_cmd(cmd);
  builder_.add_file(file);
  builder_.add_ptrace_flags(ptrace_flags);
  builder_.add_suid(suid);
  builder_.add_egid(egid);
  builder_.add_euid(euid);
  builder_.add_rgid(rgid);
  builder_.add_ruid(ruid);
  builder_.add_ppid(ppid);
  builder_.add_pid(pid);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Process> CreateProcessDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t pid = 0,
    uint32_t ppid = 0,
    uint32_t ruid = 0,
    uint32_t rgid = 0,
    uint32_t euid = 0,
    uint32_t egid = 0,
    uint32_t suid = 0,
    uint64_t cgroup_id = 0,
    uint64_t start_time = 0,
    uint32_t ptrace_flags = 0,
    ::flatbuffers::Offset<owlsm::fb::File> file = 0,
    const char *cmd = nullptr,
    const owlsm::fb::StdioFileDescriptors *stdio_file_descriptors_at_process_creation = nullptr,
    const char *shell_command = nullptr) {
  auto cmd__ = cmd ? _fbb.CreateString(cmd) : 0;
  auto shell_command__ = shell_command ? _fbb.CreateString(shell_command) : 0;
  return owlsm::fb::CreateProcess(
      _fbb,
      pid,
      ppid,
      ruid,
      rgid,
      euid,
      egid,
      suid,
      cgroup_id,
      start_time,
      ptrace_flags,
      file,
      cmd__,
      stdio_file_descriptors_at_process_creation,
      shell_command__);
}

struct RuleMetadata FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RuleMetadataBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.RuleMetadata";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DESCRIPTION = 4
  };
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           verifier.EndTable();
  }
};

struct RuleMetadataBuilder {
  typedef RuleMetadata Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(RuleMetadata::VT_DESCRIPTION, description);
  }
  explicit RuleMetadataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RuleMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RuleMetadata>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RuleMetadata> CreateRuleMetadata(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0) {
  RuleMetadataBuilder builder_(_fbb);
  builder_.add_description(description);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RuleMetadata> CreateRuleMetadataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *description = nullptr) {
  auto description__ = description ? _fbb.CreateString(description) : 0;
  return owlsm::fb::CreateRuleMetadata(
      _fbb,
      description__);
}

struct Target FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TargetBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.Target";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FILE = 4,
    VT_PROCESS = 6
  };
  const owlsm::fb::File *file() const {
    return GetPointer<const owlsm::fb::File *>(VT_FILE);
  }
  const owlsm::fb::Process *process() const {
    return GetPointer<const owlsm::fb::Process *>(VT_PROCESS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FILE) &&
           verifier.VerifyTable(file()) &&
           VerifyOffset(verifier, VT_PROCESS) &&
           verifier.VerifyTable(process()) &&
           verifier.EndTable();
  }
};

struct TargetBuilder {
  typedef Target Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_file(::flatbuffers::Offset<owlsm::fb::File> file) {
    fbb_.AddOffset(Target::VT_FILE, file);
  }
  void add_process(::flatbuffers::Offset<owlsm::fb::Process> process) {
    fbb_.AddOffset(Target::VT_PROCESS, process);
  }
  explicit TargetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Target> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Target>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Target> CreateTarget(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<owlsm::fb::File> file = 0,
    ::flatbuffers::Offset<owlsm::fb::Process> process = 0) {
  TargetBuilder builder_(_fbb);
  builder_.add_process(process);
  builder_.add_file(file);
  return builder_.Finish();
}

struct ChmodInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChmodInfoBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.ChmodInfo";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REQUESTED_MODE = 4
  };
  uint16_t requested_mode() const {
    return GetField<uint16_t>(VT_REQUESTED_MODE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_REQUESTED_MODE, 2) &&
           verifier.EndTable();
  }
};

struct ChmodInfoBuilder {
  typedef ChmodInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_requested_mode(uint16_t requested_mode) {
    fbb_.AddElement<uint16_t>(ChmodInfo::VT_REQUESTED_MODE, requested_mode, 0);
  }
  explicit ChmodInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ChmodInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ChmodInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ChmodInfo> CreateChmodInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t requested_mode = 0) {
  ChmodInfoBuilder builder_(_fbb);
  builder_.add_requested_mode(requested_mode);
  return builder_.Finish();
}

struct ChownInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChownInfoBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.ChownInfo";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REQUESTED_OWNER_UID = 4,
    VT_REQUESTED_OWNER_GID = 6
  };
  uint32_t requested_owner_uid() const {
    return GetField<uint32_t>(VT_REQUESTED_OWNER_UID, 0);
  }
  uint32_t requested_owner_gid() const {
    return GetField<uint32_t>(VT_REQUESTED_OWNER_GID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_REQUESTED_OWNER_UID, 4) &&
           VerifyField<uint32_t>(verifier, VT_REQUESTED_OWNER_GID, 4) &&
           verifier.EndTable();
  }
};

struct ChownInfoBuilder {
  typedef ChownInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_requested_owner_uid(uint32_t requested_owner_uid) {
    fbb_.AddElement<uint32_t>(ChownInfo::VT_REQUESTED_OWNER_UID, requested_owner_uid, 0);
  }
  void add_requested_owner_gid(uint32_t requested_owner_gid) {
    fbb_.AddElement<uint32_t>(ChownInfo::VT_REQUESTED_OWNER_GID, requested_owner_gid, 0);
  }
  explicit ChownInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ChownInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ChownInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ChownInfo> CreateChownInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t requested_owner_uid = 0,
    uint32_t requested_owner_gid = 0) {
  ChownInfoBuilder builder_(_fbb);
  builder_.add_requested_owner_gid(requested_owner_gid);
  builder_.add_requested_owner_uid(requested_owner_uid);
  return builder_.Finish();
}

struct RenameInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RenameInfoBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.RenameInfo";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SOURCE_FILE = 4,
    VT_DESTINATION_FILE = 6
  };
  const owlsm::fb::File *source_file() const {
    return GetPointer<const owlsm::fb::File *>(VT_SOURCE_FILE);
  }
  const owlsm::fb::File *destination_file() const {
    return GetPointer<const owlsm::fb::File *>(VT_DESTINATION_FILE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SOURCE_FILE) &&
           verifier.VerifyTable(source_file()) &&
           VerifyOffset(verifier, VT_DESTINATION_FILE) &&
           verifier.VerifyTable(destination_file()) &&
           verifier.EndTable();
  }
};

struct RenameInfoBuilder {
  typedef RenameInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_source_file(::flatbuffers::Offset<owlsm::fb::File> source_file) {
    fbb_.AddOffset(RenameInfo::VT_SOURCE_FILE, source_file);
  }
  void add_destination_file(::flatbuffers::Offset<owlsm::fb::File> destination_file) {
    fbb_.AddOffset(RenameInfo::VT_DESTINATION_FILE, destination_file);
  }
  explicit RenameInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RenameInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RenameInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RenameInfo> CreateRenameInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<owlsm::fb::File> source_file = 0,
    ::flatbuffers::Offset<owlsm::fb::File> destination_file = 0) {
  RenameInfoBuilder builder_(_fbb);
  builder_.add_destination_file(destination_file);
  builder_.add_source_file(source_file);
  return builder_.Finish();
}

struct NetworkInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NetworkInfoBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.NetworkInfo";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DIRECTION = 4,
    VT_SOURCE_IP = 6,
    VT_DESTINATION_IP = 8,
    VT_SOURCE_PORT = 10,
    VT_DESTINATION_PORT = 12,
    VT_PROTOCOL = 14,
    VT_IP_TYPE = 16
  };
  owlsm::fb::ConnectionDirection direction() const {
    return static_cast<owlsm::fb::ConnectionDirection>(GetField<uint8_t>(VT_DIRECTION, 0));
  }
  const ::flatbuffers::String *source_ip() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_IP);
  }
  const ::flatbuffers::String *destination_ip() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESTINATION_IP);
  }
  uint16_t source_port() const {
    return GetField<uint16_t>(VT_SOURCE_PORT, 0);
  }
  uint16_t destination_port() const {
    return GetField<uint16_t>(VT_DESTINATION_PORT, 0);
  }
  uint8_t protocol() const {
    return GetField<uint8_t>(VT_PROTOCOL, 0);
  }
  uint8_t ip_type() const {
    return GetField<uint8_t>(VT_IP_TYPE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_DIRECTION, 1) &&
           VerifyOffset(verifier, VT_SOURCE_IP) &&
           verifier.VerifyString(source_ip()) &&
           VerifyOffset(verifier, VT_DESTINATION_IP) &&
           verifier.VerifyString(destination_ip()) &&
           VerifyField<uint16_t>(verifier, VT_SOURCE_PORT, 2) &&
           VerifyField<uint16_t>(verifier, VT_DESTINATION_PORT, 2) &&
           VerifyField<uint8_t>(verifier, VT_PROTOCOL, 1) &&
           VerifyField<uint8_t>(verifier, VT_IP_TYPE, 1) &&
           verifier.EndTable();
  }
};

struct NetworkInfoBuilder {
  typedef NetworkInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_direction(owlsm::fb::ConnectionDirection direction) {
    fbb_.AddElement<uint8_t>(NetworkInfo::VT_DIRECTION, static_cast<uint8_t>(direction), 0);
  }
  void add_source_ip(::flatbuffers::Offset<::flatbuffers::String> source_ip) {
    fbb_.AddOffset(NetworkInfo::VT_SOURCE_IP, source_ip);
  }
  void add_destination_ip(::flatbuffers::Offset<::flatbuffers::String> destination_ip) {
    fbb_.AddOffset(NetworkInfo::VT_DESTINATION_IP, destination_ip);
  }
  void add_source_port(uint16_t source_port) {
    fbb_.AddElement<uint16_t>(NetworkInfo::VT_SOURCE_PORT, source_port, 0);
  }
  void add_destination_port(uint16_t destination_port) {
    fbb_.AddElement<uint16_t>(NetworkInfo::VT_DESTINATION_PORT, destination_port, 0);
  }
  void add_protocol(uint8_t protocol) {
    fbb_.AddElement<uint8_t>(NetworkInfo::VT_PROTOCOL, protocol, 0);
  }
  void add_ip_type(uint8_t ip_type) {
    fbb_.AddElement<uint8_t>(NetworkInfo::VT_IP_TYPE, ip_type, 0);
  }
  explicit NetworkInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NetworkInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NetworkInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NetworkInfo> CreateNetworkInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    owlsm::fb::ConnectionDirection direction = owlsm::fb::ConnectionDirection::INCOMING,
    ::flatbuffers::Offset<::flatbuffers::String> source_ip = 0,
    ::flatbuffers::Offset<::flatbuffers::String> destination_ip = 0,
    uint16_t source_port = 0,
    uint16_t destination_port = 0,
    uint8_t protocol = 0,
    uint8_t ip_type = 0) {
  NetworkInfoBuilder builder_(_fbb);
  builder_.add_destination_ip(destination_ip);
  builder_.add_source_ip(source_ip);
  builder_.add_destination_port(destination_port);
  builder_.add_source_port(source_port);
  builder_.add_ip_type(ip_type);
  builder_.add_protocol(protocol);
  builder_.add_direction(direction);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<NetworkInfo> CreateNetworkInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    owlsm::fb::ConnectionDirection direction = owlsm::fb::ConnectionDirection::INCOMING,
    const char *source_ip = nullptr,
    const char *destination_ip = nullptr,
    uint16_t source_port = 0,
    uint16_t destination_port = 0,
    uint8_t protocol = 0,
    uint8_t ip_type = 0) {
  auto source_ip__ = source_ip ? _fbb.CreateString(source_ip) : 0;
  auto destination_ip__ = destination_ip ? _fbb.CreateString(destination_ip) : 0;
  return owlsm::fb::CreateNetworkInfo(
      _fbb,
      direction,
      source_ip__,
      destination_ip__,
      source_port,
      destination_port,
      protocol,
      ip_type);
}

struct DnsAnswer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DnsAnswerBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.DnsAnswer";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_DATA_LENGTH = 6,
    VT_TTL = 8,
    VT_DATA = 10
  };
  uint16_t type() const {
    return GetField<uint16_t>(VT_TYPE, 0);
  }
  uint16_t data_length() const {
    return GetField<uint16_t>(VT_DATA_LENGTH, 0);
  }
  uint32_t ttl() const {
    return GetField<uint32_t>(VT_TTL, 0);
  }
  const ::flatbuffers::String *data() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATA);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TYPE, 2) &&
           VerifyField<uint16_t>(verifier, VT_DATA_LENGTH, 2) &&
           VerifyField<uint32_t>(verifier, VT_TTL, 4) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyString(data()) &&
           verifier.EndTable();
  }
};

struct DnsAnswerBuilder {
  typedef DnsAnswer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(uint16_t type) {
    fbb_.AddElement<uint16_t>(DnsAnswer::VT_TYPE, type, 0);
  }
  void add_data_length(uint16_t data_length) {
    fbb_.AddElement<uint16_t>(DnsAnswer::VT_DATA_LENGTH, data_length, 0);
  }
  void add_ttl(uint32_t ttl) {
    fbb_.AddElement<uint32_t>(DnsAnswer::VT_TTL, ttl, 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::String> data) {
    fbb_.AddOffset(DnsAnswer::VT_DATA, data);
  }
  explicit DnsAnswerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DnsAnswer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DnsAnswer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DnsAnswer> CreateDnsAnswer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t type = 0,
    uint16_t data_length = 0,
    uint32_t ttl = 0,
    ::flatbuffers::Offset<::flatbuffers::String> data = 0) {
  DnsAnswerBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_ttl(ttl);
  builder_.add_data_length(data_length);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DnsAnswer> CreateDnsAnswerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t type = 0,
    uint16_t data_length = 0,
    uint32_t ttl = 0,
    const char *data = nullptr) {
  auto data__ = data ? _fbb.CreateString(data) : 0;
  return owlsm::fb::CreateDnsAnswer(
      _fbb,
      type,
      data_length,
      ttl,
      data__);
}

struct DnsQueryInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DnsQueryInfoBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.DnsQueryInfo";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TXID = 4,
    VT_QUESTION = 6,
    VT_QUESTION_TYPE = 8
  };
  uint16_t txid() const {
    return GetField<uint16_t>(VT_TXID, 0);
  }
  const ::flatbuffers::String *question() const {
    return GetPointer<const ::flatbuffers::String *>(VT_QUESTION);
  }
  uint16_t question_type() const {
    return GetField<uint16_t>(VT_QUESTION_TYPE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TXID, 2) &&
           VerifyOffset(verifier, VT_QUESTION) &&
           verifier.VerifyString(question()) &&
           VerifyField<uint16_t>(verifier, VT_QUESTION_TYPE, 2) &&
           verifier.EndTable();
  }
};

struct DnsQueryInfoBuilder {
  typedef DnsQueryInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_txid(uint16_t txid) {
    fbb_.AddElement<uint16_t>(DnsQueryInfo::VT_TXID, txid, 0);
  }
  void add_question(::flatbuffers::Offset<::flatbuffers::String> question) {
    fbb_.AddOffset(DnsQueryInfo::VT_QUESTION, question);
  }
  void add_question_type(uint16_t question_type) {
    fbb_.AddElement<uint16_t>(DnsQueryInfo::VT_QUESTION_TYPE, question_type, 0);
  }
  explicit DnsQueryInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DnsQueryInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DnsQueryInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DnsQueryInfo> CreateDnsQueryInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t txid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> question = 0,
    uint16_t question_type = 0) {
  DnsQueryInfoBuilder builder_(_fbb);
  builder_.add_question(question);
  builder_.add_question_type(question_type);
  builder_.add_txid(txid);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DnsQueryInfo> CreateDnsQueryInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t txid = 0,
    const char *question = nullptr,
    uint16_t question_type = 0) {
  auto question__ = question ? _fbb.CreateString(question) : 0;
  return owlsm::fb::CreateDnsQueryInfo(
      _fbb,
      txid,
      question__,
      question_type);
}

struct DnsResponseInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DnsResponseInfoBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.DnsResponseInfo";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TXID = 4,
    VT_QUESTION = 6,
    VT_QUESTION_TYPE = 8,
    VT_ANSWER_COUNT = 10,
    VT_RCODE = 12,
    VT_ANSWERS = 14
  };
  uint16_t txid() const {
    return GetField<uint16_t>(VT_TXID, 0);
  }
  const ::flatbuffers::String *question() const {
    return GetPointer<const ::flatbuffers::String *>(VT_QUESTION);
  }
  uint16_t question_type() const {
    return GetField<uint16_t>(VT_QUESTION_TYPE, 0);
  }
  uint16_t answer_count() const {
    return GetField<uint16_t>(VT_ANSWER_COUNT, 0);
  }
  uint8_t rcode() const {
    return GetField<uint8_t>(VT_RCODE, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<owlsm::fb::DnsAnswer>> *answers() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<owlsm::fb::DnsAnswer>> *>(VT_ANSWERS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TXID, 2) &&
           VerifyOffset(verifier, VT_QUESTION) &&
           verifier.VerifyString(question()) &&
           VerifyField<uint16_t>(verifier, VT_QUESTION_TYPE, 2) &&
           VerifyField<uint16_t>(verifier, VT_ANSWER_COUNT, 2) &&
           VerifyField<uint8_t>(verifier, VT_RCODE, 1) &&
           VerifyOffset(verifier, VT_ANSWERS) &&
           verifier.VerifyVector(answers()) &&
           verifier.VerifyVectorOfTables(answers()) &&
           verifier.EndTable();
  }
};

struct DnsResponseInfoBuilder {
  typedef DnsResponseInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_txid(uint16_t txid) {
    fbb_.AddElement<uint16_t>(DnsResponseInfo::VT_TXID, txid, 0);
  }
  void add_question(::flatbuffers::Offset<::flatbuffers::String> question) {
    fbb_.AddOffset(DnsResponseInfo::VT_QUESTION, question);
  }
  void add_question_type(uint16_t question_type) {
    fbb_.AddElement<uint16_t>(DnsResponseInfo::VT_QUESTION_TYPE, question_type, 0);
  }
  void add_answer_count(uint16_t answer_count) {
    fbb_.AddElement<uint16_t>(DnsResponseInfo::VT_ANSWER_COUNT, answer_count, 0);
  }
  void add_rcode(uint8_t rcode) {
    fbb_.AddElement<uint8_t>(DnsResponseInfo::VT_RCODE, rcode, 0);
  }
  void add_answers(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<owlsm::fb::DnsAnswer>>> answers) {
    fbb_.AddOffset(DnsResponseInfo::VT_ANSWERS, answers);
  }
  explicit DnsResponseInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DnsResponseInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DnsResponseInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DnsResponseInfo> CreateDnsResponseInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t txid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> question = 0,
    uint16_t question_type = 0,
    uint16_t answer_count = 0,
    uint8_t rcode = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<owlsm::fb::DnsAnswer>>> answers = 0) {
  DnsResponseInfoBuilder builder_(_fbb);
  builder_.add_answers(answers);
  builder_.add_question(question);
  builder_.add_answer_count(answer_count);
  builder_.add_question_type(question_type);
  builder_.add_txid(txid);
  builder_.add_rcode(rcode);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DnsResponseInfo> CreateDnsResponseInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t txid = 0,
    const char *question = nullptr,
    uint16_t question_type = 0,
    uint16_t answer_count = 0,
    uint8_t rcode = 0,
    const std::vector<::flatbuffers::Offset<owlsm::fb::DnsAnswer>> *answers = nullptr) {
  auto question__ = question ? _fbb.CreateString(question) : 0;
  auto answers__ = answers ? _fbb.CreateVector<::flatbuffers::Offset<owlsm::fb::DnsAnswer>>(*answers) : 0;
  return owlsm::fb::CreateDnsResponseInfo(
      _fbb,
      txid,
      question__,
      question_type,
      answer_count,
      rcode,
      answers__);
}

struct GenericFileEventData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GenericFileEventDataBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.GenericFileEventData";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET = 4
  };
  const owlsm::fb::Target *target() const {
    return GetPointer<const owlsm::fb::Target *>(VT_TARGET);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TARGET) &&
           verifier.VerifyTable(target()) &&
           verifier.EndTable();
  }
};

struct GenericFileEventDataBuilder {
  typedef GenericFileEventData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target(::flatbuffers::Offset<owlsm::fb::Target> target) {
    fbb_.AddOffset(GenericFileEventData::VT_TARGET, target);
  }
  explicit GenericFileEventDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GenericFileEventData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GenericFileEventData>(end);
    fbb_.Required(o, GenericFileEventData::VT_TARGET);
    return o;
  }
};

inline ::flatbuffers::Offset<GenericFileEventData> CreateGenericFileEventData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<owlsm::fb::Target> target = 0) {
  GenericFileEventDataBuilder builder_(_fbb);
  builder_.add_target(target);
  return builder_.Finish();
}

struct ChownEventData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChownEventDataBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.ChownEventData";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET = 4,
    VT_CHOWN = 6
  };
  const owlsm::fb::Target *target() const {
    return GetPointer<const owlsm::fb::Target *>(VT_TARGET);
  }
  const owlsm::fb::ChownInfo *chown() const {
    return GetPointer<const owlsm::fb::ChownInfo *>(VT_CHOWN);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TARGET) &&
           verifier.VerifyTable(target()) &&
           VerifyOffsetRequired(verifier, VT_CHOWN) &&
           verifier.VerifyTable(chown()) &&
           verifier.EndTable();
  }
};

struct ChownEventDataBuilder {
  typedef ChownEventData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target(::flatbuffers::Offset<owlsm::fb::Target> target) {
    fbb_.AddOffset(ChownEventData::VT_TARGET, target);
  }
  void add_chown(::flatbuffers::Offset<owlsm::fb::ChownInfo> chown) {
    fbb_.AddOffset(ChownEventData::VT_CHOWN, chown);
  }
  explicit ChownEventDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ChownEventData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ChownEventData>(end);
    fbb_.Required(o, ChownEventData::VT_TARGET);
    fbb_.Required(o, ChownEventData::VT_CHOWN);
    return o;
  }
};

inline ::flatbuffers::Offset<ChownEventData> CreateChownEventData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<owlsm::fb::Target> target = 0,
    ::flatbuffers::Offset<owlsm::fb::ChownInfo> chown = 0) {
  ChownEventDataBuilder builder_(_fbb);
  builder_.add_chown(chown);
  builder_.add_target(target);
  return builder_.Finish();
}

struct ChmodEventData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChmodEventDataBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.ChmodEventData";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET = 4,
    VT_CHMOD = 6
  };
  const owlsm::fb::Target *target() const {
    return GetPointer<const owlsm::fb::Target *>(VT_TARGET);
  }
  const owlsm::fb::ChmodInfo *chmod() const {
    return GetPointer<const owlsm::fb::ChmodInfo *>(VT_CHMOD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TARGET) &&
           verifier.VerifyTable(target()) &&
           VerifyOffsetRequired(verifier, VT_CHMOD) &&
           verifier.VerifyTable(chmod()) &&
           verifier.EndTable();
  }
};

struct ChmodEventDataBuilder {
  typedef ChmodEventData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target(::flatbuffers::Offset<owlsm::fb::Target> target) {
    fbb_.AddOffset(ChmodEventData::VT_TARGET, target);
  }
  void add_chmod(::flatbuffers::Offset<owlsm::fb::ChmodInfo> chmod) {
    fbb_.AddOffset(ChmodEventData::VT_CHMOD, chmod);
  }
  explicit ChmodEventDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ChmodEventData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ChmodEventData>(end);
    fbb_.Required(o, ChmodEventData::VT_TARGET);
    fbb_.Required(o, ChmodEventData::VT_CHMOD);
    return o;
  }
};

inline ::flatbuffers::Offset<ChmodEventData> CreateChmodEventData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<owlsm::fb::Target> target = 0,
    ::flatbuffers::Offset<owlsm::fb::ChmodInfo> chmod = 0) {
  ChmodEventDataBuilder builder_(_fbb);
  builder_.add_chmod(chmod);
  builder_.add_target(target);
  return builder_.Finish();
}

struct ExecEventData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ExecEventDataBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.ExecEventData";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET = 4
  };
  const owlsm::fb::Target *target() const {
    return GetPointer<const owlsm::fb::Target *>(VT_TARGET);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TARGET) &&
           verifier.VerifyTable(target()) &&
           verifier.EndTable();
  }
};

struct ExecEventDataBuilder {
  typedef ExecEventData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target(::flatbuffers::Offset<owlsm::fb::Target> target) {
    fbb_.AddOffset(ExecEventData::VT_TARGET, target);
  }
  explicit ExecEventDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ExecEventData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ExecEventData>(end);
    fbb_.Required(o, ExecEventData::VT_TARGET);
    return o;
  }
};

inline ::flatbuffers::Offset<ExecEventData> CreateExecEventData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<owlsm::fb::Target> target = 0) {
  ExecEventDataBuilder builder_(_fbb);
  builder_.add_target(target);
  return builder_.Finish();
}

struct ForkEventData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ForkEventDataBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.ForkEventData";
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct ForkEventDataBuilder {
  typedef ForkEventData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ForkEventDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ForkEventData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ForkEventData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ForkEventData> CreateForkEventData(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ForkEventDataBuilder builder_(_fbb);
  return builder_.Finish();
}

struct ExitEventData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ExitEventDataBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.ExitEventData";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EXIT_CODE = 4,
    VT_SIGNAL = 6
  };
  uint32_t exit_code() const {
    return GetField<uint32_t>(VT_EXIT_CODE, 0);
  }
  uint32_t signal() const {
    return GetField<uint32_t>(VT_SIGNAL, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_EXIT_CODE, 4) &&
           VerifyField<uint32_t>(verifier, VT_SIGNAL, 4) &&
           verifier.EndTable();
  }
};

struct ExitEventDataBuilder {
  typedef ExitEventData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_exit_code(uint32_t exit_code) {
    fbb_.AddElement<uint32_t>(ExitEventData::VT_EXIT_CODE, exit_code, 0);
  }
  void add_signal(uint32_t signal) {
    fbb_.AddElement<uint32_t>(ExitEventData::VT_SIGNAL, signal, 0);
  }
  explicit ExitEventDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ExitEventData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ExitEventData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ExitEventData> CreateExitEventData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t exit_code = 0,
    uint32_t signal = 0) {
  ExitEventDataBuilder builder_(_fbb);
  builder_.add_signal(signal);
  builder_.add_exit_code(exit_code);
  return builder_.Finish();
}

struct RenameEventData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RenameEventDataBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.RenameEventData";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FLAGS = 4,
    VT_RENAME = 6
  };
  uint32_t flags() const {
    return GetField<uint32_t>(VT_FLAGS, 0);
  }
  const owlsm::fb::RenameInfo *rename() const {
    return GetPointer<const owlsm::fb::RenameInfo *>(VT_RENAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_FLAGS, 4) &&
           VerifyOffsetRequired(verifier, VT_RENAME) &&
           verifier.VerifyTable(rename()) &&
           verifier.EndTable();
  }
};

struct RenameEventDataBuilder {
  typedef RenameEventData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_flags(uint32_t flags) {
    fbb_.AddElement<uint32_t>(RenameEventData::VT_FLAGS, flags, 0);
  }
  void add_rename(::flatbuffers::Offset<owlsm::fb::RenameInfo> rename) {
    fbb_.AddOffset(RenameEventData::VT_RENAME, rename);
  }
  explicit RenameEventDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RenameEventData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RenameEventData>(end);
    fbb_.Required(o, RenameEventData::VT_RENAME);
    return o;
  }
};

inline ::flatbuffers::Offset<RenameEventData> CreateRenameEventData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t flags = 0,
    ::flatbuffers::Offset<owlsm::fb::RenameInfo> rename = 0) {
  RenameEventDataBuilder builder_(_fbb);
  builder_.add_rename(rename);
  builder_.add_flags(flags);
  return builder_.Finish();
}

struct NetworkEventData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NetworkEventDataBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.NetworkEventData";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NETWORK = 4
  };
  const owlsm::fb::NetworkInfo *network() const {
    return GetPointer<const owlsm::fb::NetworkInfo *>(VT_NETWORK);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NETWORK) &&
           verifier.VerifyTable(network()) &&
           verifier.EndTable();
  }
};

struct NetworkEventDataBuilder {
  typedef NetworkEventData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_network(::flatbuffers::Offset<owlsm::fb::NetworkInfo> network) {
    fbb_.AddOffset(NetworkEventData::VT_NETWORK, network);
  }
  explicit NetworkEventDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NetworkEventData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NetworkEventData>(end);
    fbb_.Required(o, NetworkEventData::VT_NETWORK);
    return o;
  }
};

inline ::flatbuffers::Offset<NetworkEventData> CreateNetworkEventData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<owlsm::fb::NetworkInfo> network = 0) {
  NetworkEventDataBuilder builder_(_fbb);
  builder_.add_network(network);
  return builder_.Finish();
}

struct DnsQueryEventData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DnsQueryEventDataBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.DnsQueryEventData";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NETWORK = 4,
    VT_DNS_QUERY = 6
  };
  const owlsm::fb::NetworkInfo *network() const {
    return GetPointer<const owlsm::fb::NetworkInfo *>(VT_NETWORK);
  }
  const owlsm::fb::DnsQueryInfo *dns_query() const {
    return GetPointer<const owlsm::fb::DnsQueryInfo *>(VT_DNS_QUERY);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NETWORK) &&
           verifier.VerifyTable(network()) &&
           VerifyOffsetRequired(verifier, VT_DNS_QUERY) &&
           verifier.VerifyTable(dns_query()) &&
           verifier.EndTable();
  }
};

struct DnsQueryEventDataBuilder {
  typedef DnsQueryEventData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_network(::flatbuffers::Offset<owlsm::fb::NetworkInfo> network) {
    fbb_.AddOffset(DnsQueryEventData::VT_NETWORK, network);
  }
  void add_dns_query(::flatbuffers::Offset<owlsm::fb::DnsQueryInfo> dns_query) {
    fbb_.AddOffset(DnsQueryEventData::VT_DNS_QUERY, dns_query);
  }
  explicit DnsQueryEventDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DnsQueryEventData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DnsQueryEventData>(end);
    fbb_.Required(o, DnsQueryEventData::VT_NETWORK);
    fbb_.Required(o, DnsQueryEventData::VT_DNS_QUERY);
    return o;
  }
};

inline ::flatbuffers::Offset<DnsQueryEventData> CreateDnsQueryEventData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<owlsm::fb::NetworkInfo> network = 0,
    ::flatbuffers::Offset<owlsm::fb::DnsQueryInfo> dns_query = 0) {
  DnsQueryEventDataBuilder builder_(_fbb);
  builder_.add_dns_query(dns_query);
  builder_.add_network(network);
  return builder_.Finish();
}

struct DnsResponseEventData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DnsResponseEventDataBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.DnsResponseEventData";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NETWORK = 4,
    VT_DNS_RESPONSE = 6
  };
  const owlsm::fb::NetworkInfo *network() const {
    return GetPointer<const owlsm::fb::NetworkInfo *>(VT_NETWORK);
  }
  const owlsm::fb::DnsResponseInfo *dns_response() const {
    return GetPointer<const owlsm::fb::DnsResponseInfo *>(VT_DNS_RESPONSE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NETWORK) &&
           verifier.VerifyTable(network()) &&
           VerifyOffsetRequired(verifier, VT_DNS_RESPONSE) &&
           verifier.VerifyTable(dns_response()) &&
           verifier.EndTable();
  }
};

struct DnsResponseEventDataBuilder {
  typedef DnsResponseEventData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_network(::flatbuffers::Offset<owlsm::fb::NetworkInfo> network) {
    fbb_.AddOffset(DnsResponseEventData::VT_NETWORK, network);
  }
  void add_dns_response(::flatbuffers::Offset<owlsm::fb::DnsResponseInfo> dns_response) {
    fbb_.AddOffset(DnsResponseEventData::VT_DNS_RESPONSE, dns_response);
  }
  explicit DnsResponseEventDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DnsResponseEventData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DnsResponseEventData>(end);
    fbb_.Required(o, DnsResponseEventData::VT_NETWORK);
    fbb_.Required(o, DnsResponseEventData::VT_DNS_RESPONSE);
    return o;
  }
};

inline ::flatbuffers::Offset<DnsResponseEventData> CreateDnsResponseEventData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<owlsm::fb::NetworkInfo> network = 0,
    ::flatbuffers::Offset<owlsm::fb::DnsResponseInfo> dns_response = 0) {
  DnsResponseEventDataBuilder builder_(_fbb);
  builder_.add_dns_response(dns_response);
  builder_.add_network(network);
  return builder_.Finish();
}

struct Event FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.Event";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_ACTION = 8,
    VT_MATCHED_RULE_ID = 10,
    VT_MATCHED_RULE_METADATA = 12,
    VT_HAD_ERROR = 14,
    VT_PROCESS = 16,
    VT_PARENT_PROCESS = 18,
    VT_TIME = 20,
    VT_DATA_TYPE = 22,
    VT_DATA = 24
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  owlsm::fb::EventType type() const {
    return static_cast<owlsm::fb::EventType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  owlsm::fb::Action action() const {
    return static_cast<owlsm::fb::Action>(GetField<uint8_t>(VT_ACTION, 0));
  }
  uint32_t matched_rule_id() const {
    return GetField<uint32_t>(VT_MATCHED_RULE_ID, 0);
  }
  const owlsm::fb::RuleMetadata *matched_rule_metadata() const {
    return GetPointer<const owlsm::fb::RuleMetadata *>(VT_MATCHED_RULE_METADATA);
  }
  uint8_t had_error() const {
    return GetField<uint8_t>(VT_HAD_ERROR, 0);
  }
  const owlsm::fb::Process *process() const {
    return GetPointer<const owlsm::fb::Process *>(VT_PROCESS);
  }
  const owlsm::fb::Process *parent_process() const {
    return GetPointer<const owlsm::fb::Process *>(VT_PARENT_PROCESS);
  }
  uint64_t time() const {
    return GetField<uint64_t>(VT_TIME, 0);
  }
  owlsm::fb::EventData data_type() const {
    return static_cast<owlsm::fb::EventData>(GetField<uint8_t>(VT_DATA_TYPE, 0));
  }
  const void *data() const {
    return GetPointer<const void *>(VT_DATA);
  }
  template<typename T> const T *data_as() const;
  const owlsm::fb::GenericFileEventData *data_as_GenericFileEventData() const {
    return data_type() == owlsm::fb::EventData::GenericFileEventData ? static_cast<const owlsm::fb::GenericFileEventData *>(data()) : nullptr;
  }
  const owlsm::fb::ChownEventData *data_as_ChownEventData() const {
    return data_type() == owlsm::fb::EventData::ChownEventData ? static_cast<const owlsm::fb::ChownEventData *>(data()) : nullptr;
  }
  const owlsm::fb::ChmodEventData *data_as_ChmodEventData() const {
    return data_type() == owlsm::fb::EventData::ChmodEventData ? static_cast<const owlsm::fb::ChmodEventData *>(data()) : nullptr;
  }
  const owlsm::fb::ExecEventData *data_as_ExecEventData() const {
    return data_type() == owlsm::fb::EventData::ExecEventData ? static_cast<const owlsm::fb::ExecEventData *>(data()) : nullptr;
  }
  const owlsm::fb::ForkEventData *data_as_ForkEventData() const {
    return data_type() == owlsm::fb::EventData::ForkEventData ? static_cast<const owlsm::fb::ForkEventData *>(data()) : nullptr;
  }
  const owlsm::fb::ExitEventData *data_as_ExitEventData() const {
    return data_type() == owlsm::fb::EventData::ExitEventData ? static_cast<const owlsm::fb::ExitEventData *>(data()) : nullptr;
  }
  const owlsm::fb::RenameEventData *data_as_RenameEventData() const {
    return data_type() == owlsm::fb::EventData::RenameEventData ? static_cast<const owlsm::fb::RenameEventData *>(data()) : nullptr;
  }
  const owlsm::fb::NetworkEventData *data_as_NetworkEventData() const {
    return data_type() == owlsm::fb::EventData::NetworkEventData ? static_cast<const owlsm::fb::NetworkEventData *>(data()) : nullptr;
  }
  const owlsm::fb::DnsQueryEventData *data_as_DnsQueryEventData() const {
    return data_type() == owlsm::fb::EventData::DnsQueryEventData ? static_cast<const owlsm::fb::DnsQueryEventData *>(data()) : nullptr;
  }
  const owlsm::fb::DnsResponseEventData *data_as_DnsResponseEventData() const {
    return data_type() == owlsm::fb::EventData::DnsResponseEventData ? static_cast<const owlsm::fb::DnsResponseEventData *>(data()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_ACTION, 1) &&
           VerifyField<uint32_t>(verifier, VT_MATCHED_RULE_ID, 4) &&
           VerifyOffset(verifier, VT_MATCHED_RULE_METADATA) &&
           verifier.VerifyTable(matched_rule_metadata()) &&
           VerifyField<uint8_t>(verifier, VT_HAD_ERROR, 1) &&
           VerifyOffsetRequired(verifier, VT_PROCESS) &&
           verifier.VerifyTable(process()) &&
           VerifyOffsetRequired(verifier, VT_PARENT_PROCESS) &&
           verifier.VerifyTable(parent_process()) &&
           VerifyField<uint64_t>(verifier, VT_TIME, 8) &&
           VerifyField<uint8_t>(verifier, VT_DATA_TYPE, 1) &&
           VerifyOffset(verifier, VT_DATA) &&
           VerifyEventData(verifier, data(), data_type()) &&
           verifier.EndTable();
  }
};

template<> inline const owlsm::fb::GenericFileEventData *Event::data_as<owlsm::fb::GenericFileEventData>() const {
  return data_as_GenericFileEventData();
}

template<> inline const owlsm::fb::ChownEventData *Event::data_as<owlsm::fb::ChownEventData>() const {
  return data_as_ChownEventData();
}

template<> inline const owlsm::fb::ChmodEventData *Event::data_as<owlsm::fb::ChmodEventData>() const {
  return data_as_ChmodEventData();
}

template<> inline const owlsm::fb::ExecEventData *Event::data_as<owlsm::fb::ExecEventData>() const {
  return data_as_ExecEventData();
}

template<> inline const owlsm::fb::ForkEventData *Event::data_as<owlsm::fb::ForkEventData>() const {
  return data_as_ForkEventData();
}

template<> inline const owlsm::fb::ExitEventData *Event::data_as<owlsm::fb::ExitEventData>() const {
  return data_as_ExitEventData();
}

template<> inline const owlsm::fb::RenameEventData *Event::data_as<owlsm::fb::RenameEventData>() const {
  return data_as_RenameEventData();
}

template<> inline const owlsm::fb::NetworkEventData *Event::data_as<owlsm::fb::NetworkEventData>() const {
  return data_as_NetworkEventData();
}

template<> inline const owlsm::fb::DnsQueryEventData *Event::data_as<owlsm::fb::DnsQueryEventData>() const {
  return data_as_DnsQueryEventData();
}

template<> inline const owlsm::fb::DnsResponseEventData *Event::data_as<owlsm::fb::DnsResponseEventData>() const {
  return data_as_DnsResponseEventData();
}

struct EventBuilder {
  typedef Event Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(Event::VT_ID, id, 0);
  }
  void add_type(owlsm::fb::EventType type) {
    fbb_.AddElement<uint8_t>(Event::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_action(owlsm::fb::Action action) {
    fbb_.AddElement<uint8_t>(Event::VT_ACTION, static_cast<uint8_t>(action), 0);
  }
  void add_matched_rule_id(uint32_t matched_rule_id) {
    fbb_.AddElement<uint32_t>(Event::VT_MATCHED_RULE_ID, matched_rule_id, 0);
  }
  void add_matched_rule_metadata(::flatbuffers::Offset<owlsm::fb::RuleMetadata> matched_rule_metadata) {
    fbb_.AddOffset(Event::VT_MATCHED_RULE_METADATA, matched_rule_metadata);
  }
  void add_had_error(uint8_t had_error) {
    fbb_.AddElement<uint8_t>(Event::VT_HAD_ERROR, had_error, 0);
  }
  void add_process(::flatbuffers::Offset<owlsm::fb::Process> process) {
    fbb_.AddOffset(Event::VT_PROCESS, process);
  }
  void add_parent_process(::flatbuffers::Offset<owlsm::fb::Process> parent_process) {
    fbb_.AddOffset(Event::VT_PARENT_PROCESS, parent_process);
  }
  void add_time(uint64_t time) {
    fbb_.AddElement<uint64_t>(Event::VT_TIME, time, 0);
  }
  void add_data_type(owlsm::fb::EventData data_type) {
    fbb_.AddElement<uint8_t>(Event::VT_DATA_TYPE, static_cast<uint8_t>(data_type), 0);
  }
  void add_data(::flatbuffers::Offset<void> data) {
    fbb_.AddOffset(Event::VT_DATA, data);
  }
  explicit EventBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Event> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Event>(end);
    fbb_.Required(o, Event::VT_PROCESS);
    fbb_.Required(o, Event::VT_PARENT_PROCESS);
    return o;
  }
};

inline ::flatbuffers::Offset<Event> CreateEvent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    owlsm::fb::EventType type = owlsm::fb::EventType::EXEC,
    owlsm::fb::Action action = owlsm::fb::Action::ALLOW_EVENT,
    uint32_t matched_rule_id = 0,
    ::flatbuffers::Offset<owlsm::fb::RuleMetadata> matched_rule_metadata = 0,
    uint8_t had_error = 0,
    ::flatbuffers::Offset<owlsm::fb::Process> process = 0,
    ::flatbuffers::Offset<owlsm::fb::Process> parent_process = 0,
    uint64_t time = 0,
    owlsm::fb::EventData data_type = owlsm::fb::EventData::NONE,
    ::flatbuffers::Offset<void> data = 0) {
  EventBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_id(id);
  builder_.add_data(data);
  builder_.add_parent_process(parent_process);
  builder_.add_process(process);
  builder_.add_matched_rule_metadata(matched_rule_metadata);
  builder_.add_matched_rule_id(matched_rule_id);
  builder_.add_data_type(data_type);
  builder_.add_had_error(had_error);
  builder_.add_action(action);
  builder_.add_type(type);
  return builder_.Finish();
}

struct Error FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ErrorBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "owlsm.fb.Error";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ERROR_CODE = 4,
    VT_LOCATION = 6,
    VT_DETAILS = 8,
    VT_HOOK_NAME = 10
  };
  int32_t error_code() const {
    return GetField<int32_t>(VT_ERROR_CODE, 0);
  }
  const ::flatbuffers::String *location() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LOCATION);
  }
  const ::flatbuffers::String *details() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DETAILS);
  }
  const ::flatbuffers::String *hook_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_HOOK_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ERROR_CODE, 4) &&
           VerifyOffsetRequired(verifier, VT_LOCATION) &&
           verifier.VerifyString(location()) &&
           VerifyOffsetRequired(verifier, VT_DETAILS) &&
           verifier.VerifyString(details()) &&
           VerifyOffset(verifier, VT_HOOK_NAME) &&
           verifier.VerifyString(hook_name()) &&
           verifier.EndTable();
  }
};

struct ErrorBuilder {
  typedef Error Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_error_code(int32_t error_code) {
    fbb_.AddElement<int32_t>(Error::VT_ERROR_CODE, error_code, 0);
  }
  void add_location(::flatbuffers::Offset<::flatbuffers::String> location) {
    fbb_.AddOffset(Error::VT_LOCATION, location);
  }
  void add_details(::flatbuffers::Offset<::flatbuffers::String> details) {
    fbb_.AddOffset(Error::VT_DETAILS, details);
  }
  void add_hook_name(::flatbuffers::Offset<::flatbuffers::String> hook_name) {
    fbb_.AddOffset(Error::VT_HOOK_NAME, hook_name);
  }
  explicit ErrorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Error> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Error>(end);
    fbb_.Required(o, Error::VT_LOCATION);
    fbb_.Required(o, Error::VT_DETAILS);
    return o;
  }
};

inline ::flatbuffers::Offset<Error> CreateError(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t error_code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> location = 0,
    ::flatbuffers::Offset<::flatbuffers::String> details = 0,
    ::flatbuffers::Offset<::flatbuffers::String> hook_name = 0) {
  ErrorBuilder builder_(_fbb);
  builder_.add_hook_name(hook_name);
  builder_.add_details(details);
  builder_.add_location(location);
  builder_.add_error_code(error_code);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Error> CreateErrorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t error_code = 0,
    const char *location = nullptr,
    const char *details = nullptr,
    const char *hook_name = nullptr) {
  auto location__ = location ? _fbb.CreateString(location) : 0;
  auto details__ = details ? _fbb.CreateString(details) : 0;
  auto hook_name__ = hook_name ? _fbb.CreateString(hook_name) : 0;
  return owlsm::fb::CreateError(
      _fbb,
      error_code,
      location__,
      details__,
      hook_name__);
}

template <bool B>
inline bool VerifyEventData(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, EventData type) {
  switch (type) {
    case EventData::NONE: {
      return true;
    }
    case EventData::GenericFileEventData: {
      auto ptr = reinterpret_cast<const owlsm::fb::GenericFileEventData *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventData::ChownEventData: {
      auto ptr = reinterpret_cast<const owlsm::fb::ChownEventData *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventData::ChmodEventData: {
      auto ptr = reinterpret_cast<const owlsm::fb::ChmodEventData *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventData::ExecEventData: {
      auto ptr = reinterpret_cast<const owlsm::fb::ExecEventData *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventData::ForkEventData: {
      auto ptr = reinterpret_cast<const owlsm::fb::ForkEventData *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventData::ExitEventData: {
      auto ptr = reinterpret_cast<const owlsm::fb::ExitEventData *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventData::RenameEventData: {
      auto ptr = reinterpret_cast<const owlsm::fb::RenameEventData *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventData::NetworkEventData: {
      auto ptr = reinterpret_cast<const owlsm::fb::NetworkEventData *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventData::DnsQueryEventData: {
      auto ptr = reinterpret_cast<const owlsm::fb::DnsQueryEventData *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventData::DnsResponseEventData: {
      auto ptr = reinterpret_cast<const owlsm::fb::DnsResponseEventData *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyEventDataVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<EventData> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyEventData(
        verifier,  values->Get(i), types->GetEnum<EventData>(i))) {
      return false;
    }
  }
  return true;
}

inline const owlsm::fb::Event *GetEvent(const void *buf) {
  return ::flatbuffers::GetRoot<owlsm::fb::Event>(buf);
}

inline const owlsm::fb::Event *GetSizePrefixedEvent(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<owlsm::fb::Event>(buf);
}

template <bool B = false>
inline bool VerifyEventBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<owlsm::fb::Event>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedEventBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<owlsm::fb::Event>(nullptr);
}

inline void FinishEventBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<owlsm::fb::Event> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEventBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<owlsm::fb::Event> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fb
}  // namespace owlsm

#endif  // FLATBUFFERS_GENERATED_OWLSMEVENTS_OWLSM_FB_H_
